---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  labels:
    app: webserver
    author: jobair
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
      author: jobair
  template:
    metadata:
      name: nginx-pod
      labels:
        name: nginx
        author: jobair
    spec:
      containers:
        - name: nginx-con
          image: nginx
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    creators: jobair
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: nginx
    author: jobair
...
