---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: httpd
    author: jobair
spec:
  containers:
    - name: httpd-con
      image: httpd
      volumeMounts:
        - name: myvolume
          mountPath: /usr/local/apache2/htdocs
  volumes:
    - name: myvolume
      emptyDir: {}
...
