---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    author: jobair
spec:
  containers:
    - name: nginx-con
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: slave1
              operator: In
              values:
                - jobair1
...
