---
apiVersion: v1
kind: Pod
metadata:
  name: adminer-pod
spec:
  containers:
  - name: adminer-con
    image: adminer
    ports:
    - containerPort: 8080
      hostPort: 8080
    env:
    - name: password
      valueFrom:
        secretKeyRef:          # FIXED INDENTATION
          name: adminer-s
          key: job
...

