---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: webserver
    author: jobair
spec:
  containers:
    - name: httpd-con
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 80
      resources:
        requests:
          cpu: "200m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
...
