---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    type: database
    author: jobair
spec:
  containers:
    - name: mydb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: jobair
        - name: POSTGRES_DB
          value: data
        - name: POSTGRES_USER
          value: job
...
