---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    app: ci-cd
    created: jobair

spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 9090
...
