---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
    author: jobair
spec:
  containers:
    - name: mysql-con
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: jobair
      volumeMounts:
        - name: my-volume
          mountPath: /var/lib/mysql
  volumes:
    -  name: my-volume
       persistentVolumeClaim:
         claimName: my-pvc
...
