---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    author: jobair
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/jobairansari637/Kubernetes/data
...
