---
apiVersion: v1
kind: ReplicationController
metadata:
  name: http-rc
  labels:
    app: webserver
    author: jobair
spec:
  replicas: 3
  selector:
    app: backend
  template:
    metadata:
      name: httpd-pod
      labels:
        app: backend
        author: jobair
    spec:
      containers:
        - name: httpd-container
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080
...
