---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
  labels:
    app: webserver
    author: jobair
spec:
  replicas: 2
  selector:
    matchLabels:
      type: grafic
      creator: jobair
  template:
    metadata:
      name: jenkins-pod
      labels:
        type: grafic
        creator: jobair
    spec:
      containers:
        - name: jenkins-con
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              hostPort: 8080
...
