---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    author: jobair
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 9090
  selector:
    name: postgres
    author: jobair
...
