---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    author: wakil
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      nodePort: 30002
      port: 8080
  selector:
    name: nginx
...
