---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  labels:
    author: jobair
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      nodePort: 30001
      port: 8080
  selector:
    name: adminers
    author: jobair
...
