---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-dd
spec:
  clusterIP: None
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-stat
  labels:
    app: mysql-app
spec:
  serviceName: mysql-service
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-con
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: jobair
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: my-pvc
...

