---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-con
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
  tolerations:
    - key: slave2
      value: jobair2
      operator: Equal
      effect: NoSchedule
...
