---
apiVersion: v1
kind: Service
metadata:
  name: redis-app-service
  labels:
    author: intelliqit
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6378
  selector:
    name: redis-app
...
