---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  labels:
    app: webserver
    author: jobair
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
      author: jobair
  template:
    metadata:
      labels:
        name: nginx
        author: jobair
    spec:
      containers:
        - name: nginx-con
          image: nginx:1.28
...
